import type { ApiResult } from "../../../../core/api/apiResult";
import { demoStore } from "../../../../core/mock/demo_store";
import { mockDelay } from "../../../../core/mock/config";
import type { StudyNotesDataSource } from "../../data/dataSource/study_notes_data_source";
import type { SegmentStudyNotesResponseDto, VideoStudyNotesResponseDto } from "../model/study_notes_dto";

const notes = (title: string, videoId: number) => { const source = demoStore.getTemplateForVideo(videoId); return { title: `Study notes: ${title}`, introduction: `Use these ${source.subject} notes to connect the lecture concepts before attempting the quiz.`, sections: [{ heading: "Key concepts", explanation: [{ text: `${source.concepts[0]} provides the foundation for this section.`, type: "important" as const }, { text: source.concepts[1], type: "term" as const, tooltip: `A central ${source.subject} concept.` }], definitions: [{ term: source.concepts[0], meaning: `A core idea used throughout ${source.subject}.` }], examples: [`Apply ${source.concepts[1]} to the example discussed in the lecture.`], notes: [source.concepts[2]] }] }; };
export class MockStudyNotesDataSourceImp implements StudyNotesDataSource {
  async getVideoStudyNotes(videoId: number): Promise<ApiResult<VideoStudyNotesResponseDto>> { await mockDelay(350); const video = demoStore.getVideo(videoId); if (!video) return { success: false, error: "Video not found" }; return { success: true, data: { video_id: video.id, language: "en", cached: true, study_notes: notes(video.title, video.id), created_at: "2026-09-20T14:00:00Z", reading_time: { words: 180, minutes: 2, label: "2 min read" } } }; }
  async getSegmentStudyNotes(videoId: number, segmentId: number): Promise<ApiResult<SegmentStudyNotesResponseDto>> { await mockDelay(300); const segment = demoStore.segmentsFor(videoId).find((item) => item.id === segmentId); if (!segment) return { success: false, error: "Segment not found" }; return { success: true, data: { segment_id: segment.id, segment_number: segment.number, title: segment.title, start_time: segment.start, end_time: segment.end, language: "en", study_notes: notes(segment.title, videoId), generation_failed: false, reading_time: { words: 120, minutes: 1, label: "1 min read" } } }; }
}
